### ISSUE TITLE
Issue on using optional fields if followed documentation + Notification duplication

### ISSUE THREAD

**Issue by Gaurav-dawadi** [xtrinch/fcm-django#180] opened 2021-08-30 07:20 UTC
While using this package (v 1.0.4) i faced two issues.
[1] Cannot use fields inside Message wrapper as told by documentation.
[2] Duplication of Push Notification.

For first problem:
result = device.send_message(
                Message(
                    notification=Notification(
                        title="Something",
                        body="Something",
                        image="some ulr of image",
                    ),
                    topic="something"
                )
            )
this is giving me an error
![Screenshot from 2021-08-26 14-01-28](https://user-images.githubusercontent.com/59788318/131299719-b3366a41-7f9e-41aa-ab9f-bc24095af477.png)

I tried using many options. Using data and topic only will also give an error.
 **These options worked for me.**
result = device.send_message(
                Message(
                    notification=Notification(
                        title="some title",
                        body="some message",
                        image="some image ulr",
                    ),
                    data={},
                )
            ) 

**For second problem.**
I encountered duplicate notification. Sometime same code gives single notification but sometime duplicate. I even tried removing data field and only used notification=Notification() but same problem. Can anyone help me with this duplication problem?

**Comment by xtrinch** [comment] 2022-03-22 10:43
First bug is being tracked here: https://github.com/xtrinch/fcm-django/issues/184, until it is fixed there is an easy workaround mentioned in the issue.

For the duplication, you may have had multiple devices with same registration ID's in there. There's a flag`UPDATE_ON_DUPLICATE_REG_ID`  to let the package manage it for you. Since the issue is old, I'll close it. Feel free to re-open if you still have a problem.

**Closed by xtrinch** 2022-03-22 10:43 UTC
