### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by ziima** [xtrinch/fcm-django#79] opened 2018-12-18 09:53 UTC
I would consider application more trustworthy if it had at least some tests.

**Comment by xtrinch** [comment] 2019-05-14 05:50
Pull requests on the matter would be greatly appreaciated!

**Comment by xtrinch** [comment] 2022-03-28 20:01
Closing, duplicate of https://github.com/xtrinch/fcm-django/issues/204

**Closed by xtrinch** 2022-03-28 20:01 UTC
Labels: enhancement, help wanted
